Define client to binding agent protocol
Di-Ca-N/dropbox pull request #12
Opened 2024-08-02 12:21 UTC by felipe-gallois

Added the following messages:
- MSG_STATUS_INQUIRY
- MSG_SERVICE_STATUS
- MSG_SERVER_ADDRESS

2024-08-02 17:38 UTC, Di-Ca-N requested changes

2024-08-02 17:38 UTC, Di-Ca-N commented on common/Messages.hpp
> +typedef struct sockaddr ServerAddress;
Usar diretamente a `struct sockaddr` me parece um pouco problemático porque ela pode ter vários formatos e representações internas diferentes de dados dependendo do tipo de conexão (IPv4, IPv6, UNIX...). Por ter uma estrutura variável, ela não funcionaria bem com a função `receivePayload`, porque essa função espera um tipo com tamanho fixo e previamente conhecido, então seria necessário implementar manualmente a recepção e desserialização dessa struct.

Penso que seria melhor criar uma estrutura própria, com tamanho fixo e incluindo somente os campos que de fato temos interesse.

2024-08-03 12:48 UTC, felipe-gallois commented
Adicionei um commit tentando resolver esse problema. Poderia ter trocado o sockaddr para sockaddr_in, mas acho até que é desnecessário as demais informações, já que assumimos que o protocolo que usamos é IPV4. Deixei então apenas o ip e a porta como informações.

Além disso, mudei um pouco a definição de ServiceStatus para deixar mais explícita.

2024-08-03 13:13 UTC, Di-Ca-N approved these changes
Ótimo!

2024-08-03 13:35 UTC, merged